#!/bin/bash
#COBALT -t 90
#COBALT -n 128
#COBALT --attrs mcdram=cache:numa=quad
#COBALT -A CSC250STMS07

echo "Starting Cobalt job script"
export n_nodes=$COBALT_JOBSIZE
echo $n_nodes
export n_mpi_ranks_per_node=1
echo $n_mpi_ranks_per_node
export n_mpi_ranks=$(($n_nodes * $n_mpi_ranks_per_node))

aprun  -n $n_mpi_ranks -N $n_mpi_ranks_per_node  \
  ../../phase_field-opt  -i 3D_6000_gr_split.i  --split-mesh 8193 --split-file 3D_6000_gr_split.cpr \
